# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e482deaa969fe42b64855bc69a88b2f94f8f42755a5a3d87ae28bd83e1a129be835138dea974a47d7cbc7669f784bda91d818c6bdbdccaf240ee98f8f68043d1

test:
  secret_key_base: 4f52cc0de712cd788ec9930fd4e66f337e025e2ae0d605e5e78502e75e1ecf4dfd49a7ef640652a03160feaed65a4308e31e25a070cca947452190a70c53b6de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
